---
- name: Gather the package facts
  package_facts:
    manager: auto

- set_fact:
    kodo_endpoints_installed: "{{ 'kodo-for-endpoints' in ansible_facts.packages }}"

- name: Configure OS
  include_tasks: setup_os.yml

- name: Configure storage
  include_tasks: setup_storage.yml

- name: Configure networking
  include_tasks: setup_networking.yml

- name: Install IBM Spectrum Protect
  include_tasks: install_isp.yml
  when: not kodo_endpoints_installed

- name: Configure IBM Spectrum Protect
  include_tasks: configure_isp.yml
  when: not kodo_endpoints_installed