---
- name: Configure OS
  include_tasks: setup_os.yml

- name: Configure storage
  include_tasks: setup_storage.yml

- name: Configure networking
  include_tasks: setup_networking.yml

- name: Install IBM Spectrum Protect
  include_tasks: install_isp.yml